export const COMPONENTS_REQUEST = 'COMPONENTS_REQUEST'
export const COMPONENTS_SUCCESS = 'COMPONENTS_SUCCESS'
export const COMPONENTS_FAILURE = 'COMPONENTS_FAILURE'

export const CHANGE_AUDIO_SWITCH_REQUEST = 'CHANGE_AUDIO_SWITCH_REQUEST'
export const CHANGE_AUDIO_SWITCH_SUCCESS = 'CHANGE_AUDIO_SWITCH_SUCCESS'
export const CHANGE_AUDIO_SWITCH_FAILURE = 'CHANGE_AUDIO_SWITCH_FAILURE'


export const UP_BLIND_REQUEST = 'UP_BLIND_REQUEST'
export const UP_BLIND_SUCCESS = 'UP_BLIND_SUCCESS'
export const UP_BLIND_FAILURE = 'UP_BLIND_FAILURE'

export const DOWN_BLIND_REQUEST = 'DOWN_BLIND_REQUEST'
export const DOWN_BLIND_SUCCESS = 'DOWN_BLIND_SUCCESS'
export const DOWN_BLIND_FAILURE = 'DOWN_BLIND_FAILURE'
